# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_action_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cb_subplot_id = QtWidgets.QComboBox(Form)
        self.cb_subplot_id.setObjectName("cb_subplot_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_subplot_id)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.db_action_date = QtWidgets.QDateEdit(Form)
        self.db_action_date.setDateTime(QtCore.QDateTime(QtCore.QDate(2026, 3, 25), QtCore.QTime(0, 0, 0)))
        self.db_action_date.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.db_action_date.setObjectName("db_action_date")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.db_action_date)
        self.verticalLayout.addLayout(self.formLayout)
        self.subform_widget = QtWidgets.QWidget(Form)
        self.subform_widget.setObjectName("subform_widget")
        self.verticalLayout.addWidget(self.subform_widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Subschlag"))
        self.label_2.setText(_translate("Form", "Datum"))
        self.db_action_date.setDisplayFormat(_translate("Form", "dd.MM.yyyy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
