# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_form_fertilizer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(297, 207)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.db_n = QtWidgets.QLineEdit(Form)
        self.db_n.setObjectName("db_n")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.db_n)
        self.db_p = QtWidgets.QLineEdit(Form)
        self.db_p.setObjectName("db_p")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.db_p)
        self.cb_type = QtWidgets.QComboBox(Form)
        self.cb_type.setObjectName("cb_type")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_type)
        self.db_k = QtWidgets.QLineEdit(Form)
        self.db_k.setObjectName("db_k")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.db_k)
        self.db_mg = QtWidgets.QLineEdit(Form)
        self.db_mg.setObjectName("db_mg")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.db_mg)
        self.db_ca = QtWidgets.QLineEdit(Form)
        self.db_ca.setObjectName("db_ca")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.db_ca)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Art"))
        self.label_2.setText(_translate("Form", "N"))
        self.label_3.setText(_translate("Form", "P"))
        self.label_4.setText(_translate("Form", "K"))
        self.label_5.setText(_translate("Form", "Mg"))
        self.label_6.setText(_translate("Form", "Ca"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
