# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_form_business.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(368, 177)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.db_name = QtWidgets.QLineEdit(Form)
        self.db_name.setObjectName("db_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.db_name)
        self.db_address = QtWidgets.QLineEdit(Form)
        self.db_address.setObjectName("db_address")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.db_address)
        self.db_telephone = QtWidgets.QLineEdit(Form)
        self.db_telephone.setObjectName("db_telephone")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.db_telephone)
        self.db_mail = QtWidgets.QLineEdit(Form)
        self.db_mail.setObjectName("db_mail")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.db_mail)
        self.db_registry = QtWidgets.QLineEdit(Form)
        self.db_registry.setObjectName("db_registry")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.db_registry)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Name"))
        self.label_2.setText(_translate("Form", "Adresse"))
        self.label_3.setText(_translate("Form", "Telefon-Nr"))
        self.label_4.setText(_translate("Form", "Email"))
        self.label_5.setText(_translate("Form", "Registrierungsnummer"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
