# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_form_subplot.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(369, 144)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.db_suffix = QtWidgets.QLineEdit(Form)
        self.db_suffix.setObjectName("db_suffix")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.db_suffix)
        self.db_size = QtWidgets.QLineEdit(Form)
        self.db_size.setObjectName("db_size")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.db_size)
        self.db_year = QtWidgets.QLineEdit(Form)
        self.db_year.setObjectName("db_year")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.db_year)
        self.cb_plot_id = QtWidgets.QComboBox(Form)
        self.cb_plot_id.setObjectName("cb_plot_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cb_plot_id)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Schlag"))
        self.label_2.setText(_translate("Form", "Suffix"))
        self.label_3.setText(_translate("Form", "Größe (in ha)"))
        self.label_4.setText(_translate("Form", "Jahr"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
