# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'input_form_sidebar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_input_form_sidebar(object):
    def setupUi(self, input_form_sidebar):
        input_form_sidebar.setObjectName("input_form_sidebar")
        input_form_sidebar.resize(343, 347)
        self.verticalLayout = QtWidgets.QVBoxLayout(input_form_sidebar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.container_widget_input_form = QtWidgets.QWidget(input_form_sidebar)
        self.container_widget_input_form.setObjectName("container_widget_input_form")
        self.verticalLayout.addWidget(self.container_widget_input_form)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_insert_update = QtWidgets.QPushButton(input_form_sidebar)
        self.btn_insert_update.setObjectName("btn_insert_update")
        self.horizontalLayout.addWidget(self.btn_insert_update)
        self.btn_delete = QtWidgets.QPushButton(input_form_sidebar)
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout.addWidget(self.btn_delete)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(input_form_sidebar)
        QtCore.QMetaObject.connectSlotsByName(input_form_sidebar)

    def retranslateUi(self, input_form_sidebar):
        _translate = QtCore.QCoreApplication.translate
        input_form_sidebar.setWindowTitle(_translate("input_form_sidebar", "Form"))
        self.btn_insert_update.setText(_translate("input_form_sidebar", "Einfügen/Bearbeiten"))
        self.btn_delete.setText(_translate("input_form_sidebar", "Löschen"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    input_form_sidebar = QtWidgets.QWidget()
    ui = Ui_input_form_sidebar()
    ui.setupUi(input_form_sidebar)
    input_form_sidebar.show()
    sys.exit(app.exec_())
